name: nick young
output: docs
static_src: static
static_dest: "."

global:
    links: data/main/links.yaml

partials:
    header: views/partials/header.tmpl
    footer: views/partials/footer.tmpl
    transitions: views/partials/transitions.tmpl
    blogheader: views/partials/blogheader.tmpl
    blogfooter: views/partials/blogfooter.tmpl
    postheader: views/partials/postheader.tmpl

pages:
    - title: home
      path: /
      template: views/index.tmpl
      data:
          about: data/main/about.yaml
          headlines: data/main/headlines.yaml
          experiences: data/main/experiences.yaml
          projects: data/main/projects.yaml
          misc: data/main/misc.yaml

    - title: blog
      path: /blog
      template: views/blog.tmpl
      data:
          blog: data/blog/blog.yaml

collections:
    - title: blog
      path: /blog
      template: views/post.tmpl
      posts: posts
